### ISSUE TITLE
Crash when starting the game.

### ISSUE THREAD

**Issue by Diclo** [Oth3r/MoreHeartTypes#1]
Minecraft: 1.20.1
Modloader: Quilt 0.26.0
QFAPI: qfapi-7.5.0_qsl-6.1.2_fapi-0.92.2_mc-1.20.1
More Heart Types: v1.0.0+1.20.1 [Fabric]

Error when trying to start the game.
[crash-2024-06-15_13.13.08.6056-quilt_loader.txt](https://github.com/user-attachments/files/15850603/crash-2024-06-15_13.13.08.6056-quilt_loader.txt)

**Comment by Oth3r** [comment]
fixed in 838aafd182d30c41c668cea62a10165215cd2283, thanks for the report!
